/*
 * Problem 2
 *
 * Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms. By starting with 1 and 2, the first 10 terms will be:
 *   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed
 * four million, find the sum of the even-valued terms.
 */

#include <stdio.h>

#define SEQUENCE_MAX	4000000

int
main(int argc, char *argv[])
{
	int sum;
	int f1, f2, tmp;

	sum = 0;
	for (f1 = 1, f2 = 1; f2 <= SEQUENCE_MAX;
	     tmp = f1, f1 = f2, f2 = tmp + f1) {
		if (f2 % 2 == 0)
			sum += f2;
	}
	printf("%d\n", sum);
	return 0;
}
