#!/usr/bin/env python2
# -*- coding: utf-8 -*-

'''
Problem 12
The sequence of triangle numbers is generated by adding the natural numbers.
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
The first ten terms would be:

  1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

   1: 1
   3: 1,3
   6: 1,2,3,6
  10: 1,2,5,10
  15: 1,3,5,15
  21: 1,3,7,21
  28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
'''

def triangle():
  '''generator of triangle number'''
  num = n = 0
  while True:
    n += 1
    num += n
    yield num

def nfactors(n):
  '''return number of factor'''
  num = 0
  for i in range(1,(n+1)/2):
    if n % i == 0:
      num += 1
  return num+1

def main():
  '''main function'''
  for n in triangle():
    if nfactors(n) >= 500:
      print n
      return # exit program

if __name__ == '__main__':
  main()
