/*
 * Triangle, pentagonal, and hexagonal numbers are generated by the following
 * formulae:
 *
 *   Triangle     T(n) = n(n+1)/2      1, 3, 6, 10, 15, ...
 *   Pentagonal   P(n) = n(3n-1)/2     1, 5, 12, 22, 35, ...
 *   Hexagonal    H(n) = n(2n-1)       1, 6, 15, 28, 45, ...
 *
 * It can be verified that T(285) = P(165) = H(143) = 40755.
 * Find the next triangle number that is also pentagonal and hexagonal.
 */

#include <limits.h>
#include <stdio.h>

/* typedef for function T(x),P(x),H(x) */
typedef long (*pfunc_t)(int);

static long func_t(int);
static long func_p(int);
static long func_h(int);
static int min_index(long *, int);
static int equal(long *, int);

#define NARRAY(x)	(sizeof(x)/sizeof(x[0]))


int
main(int argc, char *argv[])
{
	int idx[3] = {285,165,143};
	long val[3];
	pfunc_t func[3] = {func_t, func_p, func_h};
	int i;

	/* initialize T(2),P(2),H(2) */
	for (i = 0; i < 3; i++)
		val[i] = func[i](idx[i]);

	while (1) {
		i = min_index(val, NARRAY(val));
		idx[i]++;
		val[i] = func[i](idx[i]);
		if (equal(val, NARRAY(val)))
			break;
	}

	printf("%ld\n", val[0]);
	return 0;
}


/*
 * functions T(x),P(x),H(x)
 */
static long
func_t(int x)
{
	return (long)x * (x+1) / 2;
}

static long
func_p(int x)
{
	return (long)x * (3*x-1) / 2;
}

static long
func_h(int x)
{
	return (long)x * (2*x-1);
}


/*
 * return index of minimam value in array
 */
static int
min_index(long *array, int sz)
{
	long min = LONG_MAX;
	int idx = -1, i;
	for (i = 0; i < sz; i++) {
		if (array[i] < min) {
			min = array[i];
			idx = i;
		}
	}
	return idx;
}

/*
 * check all elem of array is equal
 */
static int
equal(long *array, int sz)
{
	int i;
	for (i = 1; i < sz; i++) {
		if (array[i-1] != array[i]) {
			/* not equal */
			return 0;
		}
	}
	return 1;
}

