/*
 * Pentagonal numbers are generated by the formula, P(n) = n * (3 * n - 1) / 2.
 * The first ten pentagonal numbers are:
 *
 * 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
 *
 * It can be seen that P(4) + P(7) = 22 + 70 = 92 = P(8). However, their
 * difference, 70 - 22 = 48, is not pentagonal.
 *
 * Find the pair of pentagonal numbers, P(j) and P(k), for which their sum and
 * difference is pentagonal and D = |P(k) - P(j)| is minimised; what is the
 * value of D?
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static long pentagonal(int);
static long *create_pentagonals(int, long *);
static int bin_search(long *, long, int);
#define SEARCH_NOTFOUND		-1
#define SEARCH_SMALL		-2

int
main(int argc, char *argv[])
{
	long *ps;   /* array of pentagonal number */
	int idx = 1, i, j, found = 0, tmp;

	ps = NULL;  /* initialize for use realloc */
	for (i = 0; ; i++) {
		if (i >= idx) {
			/* target is over current buffer */
			idx *= 10;
			ps = create_pentagonals(idx, ps);
		}
		for (j = i-1; j >=0; j--) {
			if (bin_search(ps, ps[i] - ps[j], idx) == SEARCH_NOTFOUND)
				/* ps[i]-ps[j] is not pentagonal */
				continue;
			tmp = bin_search(ps, ps[i] + ps[j], idx);
			while (tmp == SEARCH_SMALL) {
				idx *= 10;
				ps = create_pentagonals(idx, ps);
				tmp = bin_search(ps, ps[i] + ps[j], idx);
			}
			if (tmp >= 0) {
				/* ps[i]+ps[j] is pentagonal found! */
				found = 1;
				break;
			}
		}
		if (found)
			break;
	}

	printf("%ld\n", ps[i]-ps[j]);

	return 0;
}


/*
 * pentagonal number of n
 */
static long
pentagonal(int n)
{
	return (long)n * (3 * n - 1) / 2;
}


static long *
create_pentagonals(int n, long *old)
{
	long *ptr, i;
	ptr = realloc(old, n * sizeof(long));
	if (!ptr)
		return 0;
	/* XXX: initialize all heap */
	memset(ptr, 0, n * sizeof(long));
	for (i = 0; i < n; i++)
		ptr[i] = pentagonal(i+1);
	return ptr;
}


static int
bin_search(long *array, long target, int len)
{
	int idx1 = 0, idx2 = len - 1;
	int idx;

	if (array[idx2] < target)
		/* if array is small than target */
		return SEARCH_SMALL;

	while (idx1 <= idx2) {
		idx = (idx1 + idx2) / 2;
		if (array[idx] == target)
			return idx;
		if (array[idx] > target)
			idx2 = idx-1;
		else
			idx1 = idx+1;
	}
	/* not found target value in array */
	return SEARCH_NOTFOUND;
}


